[theme]
base = "dark"
primaryColor = "#00C8F0"
backgroundColor = "#07090D"
secondaryBackgroundColor = "#0F1520"
textColor = "#DDE6F0"
font = "monospace"

[server]
maxUploadSize = 10
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
